opt_in_rules:
  - convenience_type
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - toggle_bool
analyzer_rules:
  - unused_import
included:
  - Challenge
excluded:
  - OtherFrameworks
  - Pods
